name: Graphentra Analyzer

on:
  push:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout demo application
        uses: actions/checkout@v7
        with:
          path: demo-application
          fetch-depth: 2

      - name: Checkout Graphentra analyzer
        uses: actions/checkout@v7
        with:
          repository: muhammadmohsinjs-web/graphentra-analyzer
          path: graphentra-analyzer

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Show changed files
        working-directory: demo-application
        run: git diff --name-only HEAD~1 HEAD

      - name: Install Graphentra dependencies
        working-directory: graphentra-analyzer
        run: npm ci

      - name: Run Graphentra analyzer
        working-directory: graphentra-analyzer
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENROUTER_MODEL: ${{ secrets.OPENROUTER_MODEL }}
        run: npm run analyze -- ../demo-application
