name: Lesson 2

on:
  push:

jobs:
  learn:
    runs-on: ubuntu-latest

    steps:
      - name: Show files before checkout
        run: ls -la

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Show files after checkout
        run: ls -la
