name: Lesson 2

on:
  push:

jobs:
  run-node:
    runs-on: ubuntu-latest

    steps:
      - name: Show files before checkout
        run: ls -la

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 26

      - name: Show files after checkout
        run: ls -la

      - name: node version
        run: node -v

      - name: Show npm version
        run: npm --version

      - name: Install dependencies
        run: npm ci

      - name: Run application
        run: npm start
